apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: NodePort
  selector:
      app: python_app_pod
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005